// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . e e e . . . . . . 
. . . . . . . 1 . . e . . . . . 
. . . . . . . 1 . . . e . . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . . e . . . 
. . . . . . . 1 . . . e . . . . 
. . . . . . . 1 . . e . . . . . 
. . . . . . . e e e . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":return img`
......ffff..............
....ffffffff............
...ffffffffff...........
..ffeeeffeeeff..........
..ffffeeeeffff..........
..f1111111111f..........
..f1227777221f......ccc.
.ff1111111111ff....cddc.
.ffffffffffffff...cddc..
.ffffffffffffff.ccddc...
fdfff222f9fffff3cddc....
fbfffff2f9fffff3ccc.....
fbf3f99999ffffff3.......
fcf.f9f2ffffff33........
.ff.f9f222ff............
....ffffffff............
.....ff..ff.............
.....ff..ff.............
.....22..22.............
....22222222............
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
