sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    otherSprite.destroy()
    music.baDing.play()
})
let bow: Sprite = null
game.splash("\"cherry picker\"")
music.playMelody("B G B A G B G B ", 120)
tiles.setTilemap(tilemap`level1`)
let mySprite = sprites.create(img`
    ......ffff..............
    ....ffffffff............
    ...ffffffffff...........
    ..ffeeeffeeeff..........
    ..ffffeeeeffff..........
    ..f1111111111f..........
    ..f1227777221f......ccc.
    .ff1111111111ff....cddc.
    .ffffffffffffff...cddc..
    .ffffffffffffff.ccddc...
    fdfff222f9fffff3cddc....
    fbfffff2f9fffff3ccc.....
    fbf3f99999ffffff3.......
    fcf.f9f2ffffff33........
    .ff.f9f222ff............
    ....ffffffff............
    .....ff..ff.............
    .....ff..ff.............
    .....22..22.............
    ....22222222............
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 150, 150)
info.startCountdown(60)
info.setScore(0)
game.onUpdateInterval(1000, function () {
    bow = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . e e e . . . . . . 
        . . . . . . . 1 . . e . . . . . 
        . . . . . . . 1 . . . e . . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . . e . . . 
        . . . . . . . 1 . . . e . . . . 
        . . . . . . . 1 . . e . . . . . 
        . . . . . . . e e e . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    bow.setPosition(randint(0, 160), randint(0, 120))
})
